//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWD_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Master()
        {
            this.Order_Item_Master = new HashSet<Order_Item_Master>();
        }
    
        public int Order_ID { get; set; }
        public string Order_No { get; set; }
        public string Order_Type { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> User_Address_ID { get; set; }
        public string Order_Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual AdminLoginMaster AdminLoginMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item_Master> Order_Item_Master { get; set; }
        public virtual User_Address_Master User_Address_Master { get; set; }
    }
}
