//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWD_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Specification_Master
    {
        public int Product_Specification_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Specification_Title { get; set; }
        public string Specification_Value { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Specification_GroupID { get; set; }
    
        public virtual Product_Master Product_Master { get; set; }
        public virtual Specification_Group_Master Specification_Group_Master { get; set; }
    }
}
