//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWD_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Master()
        {
            this.Cart_Master = new HashSet<Cart_Master>();
            this.Order_Item_Master = new HashSet<Order_Item_Master>();
            this.Product_CK_Master = new HashSet<Product_CK_Master>();
            this.Product_Image_Master = new HashSet<Product_Image_Master>();
            this.Specification_Group_Master = new HashSet<Specification_Group_Master>();
            this.Product_Specification_Master = new HashSet<Product_Specification_Master>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Title { get; set; }
        public string Product_short_description { get; set; }
        public string Product_long_description { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> SubCategory_ID { get; set; }
        public Nullable<int> ThirdCategory_ID { get; set; }
        public Nullable<decimal> Product_Price { get; set; }
        public Nullable<bool> IsHotProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_Master> Cart_Master { get; set; }
        public virtual Category_Master Category_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item_Master> Order_Item_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_CK_Master> Product_CK_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Image_Master> Product_Image_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specification_Group_Master> Specification_Group_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Specification_Master> Product_Specification_Master { get; set; }
        public virtual SubCategory_Master SubCategory_Master { get; set; }
        public virtual ThirdCategory_Master ThirdCategory_Master { get; set; }
    }
}
