//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWD_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategory_Master()
        {
            this.Product_Master = new HashSet<Product_Master>();
            this.ThirdCategory_Master = new HashSet<ThirdCategory_Master>();
        }
    
        public int SubCategory_ID { get; set; }
        public string SubCategory_Name { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsHomePage { get; set; }
        public string ImageName { get; set; }
        public Nullable<decimal> Sortable { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public byte[] Page_Image { get; set; }
        public string Page_Image_Name { get; set; }
        public string AlterText { get; set; }
    
        public virtual Category_Master Category_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Master> Product_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThirdCategory_Master> ThirdCategory_Master { get; set; }
    }
}
