//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWD_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdCategory_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThirdCategory_Master()
        {
            this.Product_Master = new HashSet<Product_Master>();
        }
    
        public int ThirdCategory_ID { get; set; }
        public Nullable<int> SubCategory_ID { get; set; }
        public string ThirdCategory_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Master> Product_Master { get; set; }
        public virtual SubCategory_Master SubCategory_Master { get; set; }
    }
}
