//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWD_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails_Master
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string WebSite { get; set; }
        public string ProfilePhoto { get; set; }
        public string Bio { get; set; }
    
        public virtual AdminLoginMaster AdminLoginMaster { get; set; }
    }
}
