//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWD_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Address_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Address_Master()
        {
            this.Order_Master = new HashSet<Order_Master>();
        }
    
        public int User_Address_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string BName { get; set; }
        public string BEmail { get; set; }
        public string BMobile { get; set; }
        public string BAddress { get; set; }
        public string BCity { get; set; }
        public string BState { get; set; }
        public string BZipcode { get; set; }
        public string SName { get; set; }
        public string SEmail { get; set; }
        public string SMobile { get; set; }
        public string SAddress { get; set; }
        public string SCity { get; set; }
        public string SState { get; set; }
        public string SZipcode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual AdminLoginMaster AdminLoginMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Master> Order_Master { get; set; }
    }
}
