//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimp_India_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Image_Master
    {
        public int Procut_image_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public byte[] Product_image { get; set; }
        public string Image_name { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public string AlterText { get; set; }
    
        public virtual Product_Master Product_Master { get; set; }
    }
}
