//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rimp_India_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification_Group_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specification_Group_Master()
        {
            this.Product_Specification_Master = new HashSet<Product_Specification_Master>();
        }
    
        public int Specification_GroupID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Specification_Group_Name { get; set; }
    
        public virtual Product_Master Product_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Specification_Master> Product_Specification_Master { get; set; }
    }
}
